"""Register this checkout as a Maya module, or drag this file into Maya."""

import argparse
import importlib
import os
from pathlib import Path
import sys

VERSION = "0.1.0"
MODULE_NAME = "maya_volume_remesh"
MARKER = "# Generated by the Maya Volume Remesh installer.\n"


def project_root():
    # Maya drag/drop execution does not always supply a trustworthy __file__.
    return Path(project_root.__code__.co_filename).resolve().parent


def default_module_directory():
    try:
        from maya import cmds

        return Path(cmds.internalVar(userAppDir=True)) / "modules"
    except (ImportError, RuntimeError):
        app = os.environ.get("MAYA_APP_DIR")
        if app:
            return Path(app).expanduser() / "modules"
        if sys.platform == "darwin":
            return Path.home() / "Library/Preferences/Autodesk/maya/modules"
        if sys.platform == "win32":
            return Path.home() / "Documents/maya/modules"
        return Path.home() / "maya/modules"


def _activate(root):
    existing = sys.modules.get(MODULE_NAME)
    expected = root / "src" / MODULE_NAME / "__init__.py"
    if existing is not None and Path(existing.__file__).resolve() != expected:
        raise RuntimeError("Save and restart Maya before changing Maya Volume Remesh installations")
    src = str(root / "src")
    if src in sys.path:
        sys.path.remove(src)
    sys.path.insert(0, src)
    importlib.import_module(MODULE_NAME)._check_source()


def install(module_directory=None, activate=False):
    root = project_root()
    if not (root / "src/MESH_DynaMesh_CPP/dynamesh.cpp").is_file():
        raise RuntimeError("Extract the complete repository before installing")
    directory = Path(module_directory).expanduser() if module_directory else default_module_directory()
    content = MARKER + "+ {} {} {}\n".format(MODULE_NAME, VERSION, root.as_posix()) + "scripts: src\nPYTHONPATH+:=src\n"
    target = directory / (MODULE_NAME + ".mod")
    if target.exists() and not target.read_text(encoding="utf-8").startswith(MARKER):
        raise RuntimeError("Refusing to replace an existing module file: " + str(target))
    if activate:
        _activate(root)
    directory.mkdir(parents=True, exist_ok=True)
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        target.write_text(content, encoding="utf-8")
    return target


def onMayaDroppedPythonFile(*_args):
    path = install(activate=True)
    print("Maya Volume Remesh installed: " + str(path))
    print("Select meshes, then run: import maya_volume_remesh; maya_volume_remesh.create()")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--module-dir", help="Maya module directory; defaults to your Maya user modules folder")
    options = parser.parse_args()
    path = install(options.module_dir)
    print("Maya module registered: " + str(path))
    print("Restart Maya, then run: import maya_volume_remesh; maya_volume_remesh.create()")


if __name__ == "__main__":
    main()
